project_id = "oejiewwdmuhnnygnzkvw"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.handle-email-events]
    verify_jwt = false
  [functions.preview-transactional-email]
    verify_jwt = false
  [functions.send-email]
    verify_jwt = false
  [functions.send-post-received]
    verify_jwt = true
