ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS name text,
  ADD COLUMN IF NOT EXISTS entity_type text,
  ADD COLUMN IF NOT EXISTS sex text,
  ADD COLUMN IF NOT EXISTS birth_month text,
  ADD COLUMN IF NOT EXISTS birth_day text,
  ADD COLUMN IF NOT EXISTS birth_year text,
  ADD COLUMN IF NOT EXISTS city text,
  ADD COLUMN IF NOT EXISTS state text,
  ADD COLUMN IF NOT EXISTS country text,
  ADD COLUMN IF NOT EXISTS city_born text,
  ADD COLUMN IF NOT EXISTS education text,
  ADD COLUMN IF NOT EXISTS high_school text,
  ADD COLUMN IF NOT EXISTS college text,
  ADD COLUMN IF NOT EXISTS degree text,
  ADD COLUMN IF NOT EXISTS major text,
  ADD COLUMN IF NOT EXISTS job text,
  ADD COLUMN IF NOT EXISTS favorite_movie text,
  ADD COLUMN IF NOT EXISTS reading text,
  ADD COLUMN IF NOT EXISTS email_on_message boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS email_on_comment boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS email_on_follow boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS email_on_post_edit boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS email_top_posts boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS email_frequency text DEFAULT 'weekly';